apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-pipe-analysis-navigator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/pipe-analysis-navigator
    repoURL: https://github.com/lsst-dm/lsst-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
