apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/lsst-dm/lsst-sandbox.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
