apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing-page
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/landing-page
    repoURL: https://github.com/lsst-dm/lsst-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
