apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: default
  source:
    path: charts/sealed-secrets
    repoURL: https://github.com/lsst-dm/lsst-sandbox.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
