---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /vault
        pathType: Prefix
        backend:
          service:
            name: vault
            port: 
              number: 8200