---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vault-reverse-proxy
spec:
  selector:
    matchLabels:
      app: vault-reverse-proxy
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-reverse-proxy
    spec:
      containers:
      - image: nginx:1.19.0
        name: vault-reverse-proxy
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: vault-reverse-proxy-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-reverse-proxy-nginx-config
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
      
      location /vault/ {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        proxy_pass              http://vault:8200/;

        proxy_read_timeout      600s;
        proxy_send_timeout      600s;
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: vault-reverse-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: vault-reverse-proxy

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: vault
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /vault
        pathType: Prefix
        backend:
          serviceName: vault-reverse-proxy
          servicePort: 80
    