name: pipe-analysis-navigator-base

on:
  push:
    branches:
      - 'master'
    paths:
    - 'src/pipe-analysis-navigator/src/Dockerfile'
    - '.github/workflows/build-pipe-analysis-navigator-base.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: src/pipe-analysis-navigator/src
          push: true
          tags: lsstdm/pipe-analysis-navigator-base:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}