---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-argocd-server
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /argo-cd
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port: 
              number: 80
